"""initial schema

Revision ID: 7d66e133bd2b
Revises: 
Create Date: 2026-05-29 13:49:18.089902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d66e133bd2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=768), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('embedding', mysql.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('subcategories', mysql.JSON(), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('raw_data', mysql.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_articles_category', 'articles', ['category'], unique=False)
    op.create_index('ix_articles_processed', 'articles', ['is_processed'], unique=False)
    op.create_index('ix_articles_published', 'articles', ['published_at'], unique=False, mysql_length=None)
    op.create_index('ix_articles_url', 'articles', ['url'], unique=True)
    op.create_table('cluster_articles',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('cluster_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_articles')
    op.drop_index('ix_articles_url', table_name='articles')
    op.drop_index('ix_articles_published', table_name='articles', mysql_length=None)
    op.drop_index('ix_articles_processed', table_name='articles')
    op.drop_index('ix_articles_category', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
