"""change author to text

Revision ID: eb3e424d44f5
Revises: 7d66e133bd2b
Create Date: 2026-05-29 17:13:20.159715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb3e424d44f5'
down_revision: Union[str, Sequence[str], None] = '7d66e133bd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'author',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'author',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
